### PR TITLE
Implemented connect functionality

### PR DESCRIPTION
**Pull request by BaloMueller**
Data transmission will follow...

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Sounds good! Im sure you already know this, but were trying to look like these bindings files
https://github.com/sandeepmistry/noble/tree/master/lib/mac
IE we dont want to change our RNBLE.ios.js significantly from https://github.com/sandeepmistry/noble/blob/master/lib/noble.js

**Comment by BaloMueller** [comment]
I reverted the change in RNBLE.ios.js. Are there any other files I should not touch?

**Comment by jacobrosenthal** [comment]
Sorry, I wasnt saying you should remove that change. In fact your addition is IN the other file:
https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L44

No, I dont think so. And shouldn't touch is a strong phrasing :)

If your question is when this would be merged, I dont see enough functionality yet. Connect doesnt buy much really on its own.

**Comment by niftylettuce** [comment]
Where are we at here, I'd love to get this in...!

**Comment by BaloMueller** [comment]
I'm just using https://github.com/Profab/react-native-ble fork. This guy did a lot of great work!

**Pull request closed without merging**
